/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import bitcamp.java110.cms.client.ClientApp;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ClientApp classUnderTest = new ClientApp();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
